### ISSUE TITLE
Example notebooks can't be run

### ISSUE THREAD

**Issue by solresol** [h1st-ai/h1st#8]
The third cell of `examples/Forecasting/notebooks/forecast.ipynb`:

`prepared_data = m.prep_data(m.load_data())`

This fails because data is missing.
`FileNotFoundError: [Errno 2] No such file or directory: './data/train.csv'`

-----

In `examples/AutomotiveCybersecurity/notebooks/Automotive Cybersecurity - Cold Start Problem.ipynb`

`DATA_LOCATION = "COMING-SOON"
df = pd.read_parquet('%s/train/attacks/20181113_Driver1_Trip1-0.parquet' % DATA_LOCATION)`

This gets an OSError because there's no data.

**Comment by ctn** [comment]
Yeah that data is coming from Kaggle. Someone (I think @thangtp is working to make this work). Thanks for reporting @solresol .

**Comment by solresol** [comment]
Note that #21 doesn't actually fix either problem, so I'm not quite sure why the issue is closed:

Here's the failure from the Forecasting example.
`subprocess.run("mkdir` {data}".format(data=self.data_dir), shell=True, check=True)` can fail: 
`CalledProcessError: Command 'mkdir ./data' returned non-zero exit status 1.`

It might be better to use `os.mkdir` !

The line after it is problematic:
`subprocess.run("kaggle competitions download -c rossmann-store-sales -p {data}/".format(data=self.data_dir), shell=True, check=True)`

There's no documentation to say that the "kaggle" binary is needed; nor do any of the requirements files list any pypi package that might install a "kaggle" program.

-----

The cyber automative example doesn't work either, and #21 didn't even attempt to fix that problem.

**Comment by nqbao** [comment]
Hi @solresol, I think I accidentally closed the issue when I merged the PR. Since the data comes from kaggle, and it requires user to accept the license for it to work, we can not distribute the data together with the source code. @aht updated the notebook to clarify about the requirement

<img width="1090" alt="Screen Shot 2020-08-24 at 9 33 30 PM" src="https://user-images.githubusercontent.com/177742/91123357-8537fd80-e651-11ea-9464-e08214d04f6f.png">

Can you give it a try @solresol?

@aht would it be better if you also check for the `kaggle` command line and return appropriate error message to user?

**Comment by solresol** [comment]
@nqbao I'm most interested in the cybersecurity one, as that's what we've talked about using as an example in customer interviews.

**Comment by nqbao** [comment]
@aht can you help to unblock @solresol for the autocyber notebook?

**Comment by aht** [comment]
Hi @solresol I'm working to prepare the autocyber data for public release, ETA is next week.

**Comment by ctn** [comment]
What's the specific resolution of this issue? @aht @nqbao

**Comment by ctn** [comment]
Let's get this resolved by EOD folks.

**Comment by aht** [comment]
This is now resolved. Sorry I had an emergency and was not available in the last 10d to complete the task sooner.
